# -*- coding: utf-8 -*-
"""anp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WnrSBCLI-qM96LzwCcSXvl_xT5a0IitV
"""

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/ultralytics/yolov5
# %cd yolov5

!pip install -r requirements.txt

import torch
torch.cuda.is_available()

!nvidia-smi

from google.colab import drive
drive.mount('/content/drive')

data_yaml = f"""
train: /content/drive/MyDrive/project/data/images/train
val: /content/drive/MyDrive/project/data/images/val
nc: 1  # number of classes
names: ['number_plate']  # class names
"""

with open('data.yaml', 'w') as f:
    f.write(data_yaml)

import utils
display = utils.notebook_init()

with open('data.yaml', 'r') as f:
  print(f.read())

'''import os
from PIL import Image
import matplotlib.pyplot as plt

# Assuming your dataset is in '/content/drive/MyDrive/project/data/'
data_dir = '/content/drive/MyDrive/project/data'

# Iterate through a few images and their corresponding labels
for i in range(5):  # Adjust the number of images to check
  image_path = os.path.join(data_dir, 'images/train', f'{i+1}.jpg')  # Adjust the path as needed
  label_path = os.path.join(data_dir, 'label/train', f'{i+1}.txt')

  # Print image and label paths
  print(f"Image Path: {image_path}")
  print(f"Label Path: {label_path}")

  # Load and display the image
  img = Image.open(image_path)
  plt.imshow(img)
  plt.show()

  # Parse the label file (optional)
  with open(label_path, 'r') as f:
    for line in f:
      class_id, x_center, y_center, width, height = map(float, line.strip().split())
      # ... (you can use these values to visualize bounding boxes)'''

!python train.py --img 640 --batch 16 --epochs 100 --data data.yaml --weights yolov5s.pt  # Adjust arguments as needed

video_path = '/content/drive/MyDrive/project/anpr/anpr_video.mp4'
best_pt_path='/content/drive/MyDrive/project/anpr/best.pt'

!python detect.py --weights "{best_pt_path}" --source "{video_path}" --img 640 --conf 0.25